package com.zimu.domain.entity;

import java.util.Date;

public class PersistentLoginsEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persistent_logins.series
     *
     * @mbg.generated
     */
    private String series;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persistent_logins.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persistent_logins.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column persistent_logins.last_used
     *
     * @mbg.generated
     */
    private Date lastUsed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persistent_logins.series
     *
     * @return the value of persistent_logins.series
     *
     * @mbg.generated
     */
    public String getSeries() {
        return series;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persistent_logins.series
     *
     * @param series the value for persistent_logins.series
     *
     * @mbg.generated
     */
    public void setSeries(String series) {
        this.series = series == null ? null : series.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persistent_logins.username
     *
     * @return the value of persistent_logins.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persistent_logins.username
     *
     * @param username the value for persistent_logins.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persistent_logins.token
     *
     * @return the value of persistent_logins.token
     *
     * @mbg.generated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persistent_logins.token
     *
     * @param token the value for persistent_logins.token
     *
     * @mbg.generated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column persistent_logins.last_used
     *
     * @return the value of persistent_logins.last_used
     *
     * @mbg.generated
     */
    public Date getLastUsed() {
        return lastUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column persistent_logins.last_used
     *
     * @param lastUsed the value for persistent_logins.last_used
     *
     * @mbg.generated
     */
    public void setLastUsed(Date lastUsed) {
        this.lastUsed = lastUsed;
    }
}