package com.zimu.domain.entity;

import java.util.Date;

public class RequestMappingEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_request_mapping.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_request_mapping.patterns
     *
     * @mbg.generated
     */
    private String patterns;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_request_mapping.methods
     *
     * @mbg.generated
     */
    private String methods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_request_mapping.del_flag
     *
     * @mbg.generated
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_request_mapping.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_request_mapping.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_request_mapping.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_request_mapping.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_request_mapping.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_request_mapping.id
     *
     * @return the value of t_request_mapping.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_request_mapping.id
     *
     * @param id the value for t_request_mapping.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_request_mapping.patterns
     *
     * @return the value of t_request_mapping.patterns
     *
     * @mbg.generated
     */
    public String getPatterns() {
        return patterns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_request_mapping.patterns
     *
     * @param patterns the value for t_request_mapping.patterns
     *
     * @mbg.generated
     */
    public void setPatterns(String patterns) {
        this.patterns = patterns == null ? null : patterns.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_request_mapping.methods
     *
     * @return the value of t_request_mapping.methods
     *
     * @mbg.generated
     */
    public String getMethods() {
        return methods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_request_mapping.methods
     *
     * @param methods the value for t_request_mapping.methods
     *
     * @mbg.generated
     */
    public void setMethods(String methods) {
        this.methods = methods == null ? null : methods.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_request_mapping.del_flag
     *
     * @return the value of t_request_mapping.del_flag
     *
     * @mbg.generated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_request_mapping.del_flag
     *
     * @param delFlag the value for t_request_mapping.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_request_mapping.create_by
     *
     * @return the value of t_request_mapping.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_request_mapping.create_by
     *
     * @param createBy the value for t_request_mapping.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_request_mapping.create_date
     *
     * @return the value of t_request_mapping.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_request_mapping.create_date
     *
     * @param createDate the value for t_request_mapping.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_request_mapping.update_by
     *
     * @return the value of t_request_mapping.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_request_mapping.update_by
     *
     * @param updateBy the value for t_request_mapping.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_request_mapping.update_date
     *
     * @return the value of t_request_mapping.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_request_mapping.update_date
     *
     * @param updateDate the value for t_request_mapping.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_request_mapping.version
     *
     * @return the value of t_request_mapping.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_request_mapping.version
     *
     * @param version the value for t_request_mapping.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}