package com.zimu.domain.entity;

import java.util.Date;

public class UserGithubEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.github_user_id
     *
     * @mbg.generated
     */
    private Long githubUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.login
     *
     * @mbg.generated
     */
    private String login;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.avatar_url
     *
     * @mbg.generated
     */
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.gravatar_id
     *
     * @mbg.generated
     */
    private String gravatarId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.html_url
     *
     * @mbg.generated
     */
    private String htmlUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.followers_url
     *
     * @mbg.generated
     */
    private String followersUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.following_url
     *
     * @mbg.generated
     */
    private String followingUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.gists_url
     *
     * @mbg.generated
     */
    private String gistsUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.starred_url
     *
     * @mbg.generated
     */
    private String starredUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.subscriptions_url
     *
     * @mbg.generated
     */
    private String subscriptionsUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.organizations_url
     *
     * @mbg.generated
     */
    private String organizationsUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.repos_url
     *
     * @mbg.generated
     */
    private String reposUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.events_url
     *
     * @mbg.generated
     */
    private String eventsUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.received_events_url
     *
     * @mbg.generated
     */
    private String receivedEventsUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.site_admin
     *
     * @mbg.generated
     */
    private String siteAdmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.company
     *
     * @mbg.generated
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.blog
     *
     * @mbg.generated
     */
    private String blog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.location
     *
     * @mbg.generated
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.hireable
     *
     * @mbg.generated
     */
    private String hireable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.bio
     *
     * @mbg.generated
     */
    private String bio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.public_repos
     *
     * @mbg.generated
     */
    private Integer publicRepos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.public_gists
     *
     * @mbg.generated
     */
    private Integer publicGists;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.followers
     *
     * @mbg.generated
     */
    private Integer followers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.following
     *
     * @mbg.generated
     */
    private Integer following;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.private_gists
     *
     * @mbg.generated
     */
    private Integer privateGists;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.total_private_repos
     *
     * @mbg.generated
     */
    private Integer totalPrivateRepos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.owned_private_repos
     *
     * @mbg.generated
     */
    private Integer ownedPrivateRepos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.disk_usage
     *
     * @mbg.generated
     */
    private String diskUsage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.collaborators
     *
     * @mbg.generated
     */
    private Integer collaborators;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.two_factor_authentication
     *
     * @mbg.generated
     */
    private String twoFactorAuthentication;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.plan_name
     *
     * @mbg.generated
     */
    private String planName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.plan_space
     *
     * @mbg.generated
     */
    private String planSpace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.plan_collaborators
     *
     * @mbg.generated
     */
    private Integer planCollaborators;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.plan_private_repos
     *
     * @mbg.generated
     */
    private Integer planPrivateRepos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.del_flag
     *
     * @mbg.generated
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_github.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.id
     *
     * @return the value of t_user_github.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.id
     *
     * @param id the value for t_user_github.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.user_id
     *
     * @return the value of t_user_github.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.user_id
     *
     * @param userId the value for t_user_github.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.github_user_id
     *
     * @return the value of t_user_github.github_user_id
     *
     * @mbg.generated
     */
    public Long getGithubUserId() {
        return githubUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.github_user_id
     *
     * @param githubUserId the value for t_user_github.github_user_id
     *
     * @mbg.generated
     */
    public void setGithubUserId(Long githubUserId) {
        this.githubUserId = githubUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.login
     *
     * @return the value of t_user_github.login
     *
     * @mbg.generated
     */
    public String getLogin() {
        return login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.login
     *
     * @param login the value for t_user_github.login
     *
     * @mbg.generated
     */
    public void setLogin(String login) {
        this.login = login == null ? null : login.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.name
     *
     * @return the value of t_user_github.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.name
     *
     * @param name the value for t_user_github.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.avatar_url
     *
     * @return the value of t_user_github.avatar_url
     *
     * @mbg.generated
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.avatar_url
     *
     * @param avatarUrl the value for t_user_github.avatar_url
     *
     * @mbg.generated
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.gravatar_id
     *
     * @return the value of t_user_github.gravatar_id
     *
     * @mbg.generated
     */
    public String getGravatarId() {
        return gravatarId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.gravatar_id
     *
     * @param gravatarId the value for t_user_github.gravatar_id
     *
     * @mbg.generated
     */
    public void setGravatarId(String gravatarId) {
        this.gravatarId = gravatarId == null ? null : gravatarId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.url
     *
     * @return the value of t_user_github.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.url
     *
     * @param url the value for t_user_github.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.html_url
     *
     * @return the value of t_user_github.html_url
     *
     * @mbg.generated
     */
    public String getHtmlUrl() {
        return htmlUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.html_url
     *
     * @param htmlUrl the value for t_user_github.html_url
     *
     * @mbg.generated
     */
    public void setHtmlUrl(String htmlUrl) {
        this.htmlUrl = htmlUrl == null ? null : htmlUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.followers_url
     *
     * @return the value of t_user_github.followers_url
     *
     * @mbg.generated
     */
    public String getFollowersUrl() {
        return followersUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.followers_url
     *
     * @param followersUrl the value for t_user_github.followers_url
     *
     * @mbg.generated
     */
    public void setFollowersUrl(String followersUrl) {
        this.followersUrl = followersUrl == null ? null : followersUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.following_url
     *
     * @return the value of t_user_github.following_url
     *
     * @mbg.generated
     */
    public String getFollowingUrl() {
        return followingUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.following_url
     *
     * @param followingUrl the value for t_user_github.following_url
     *
     * @mbg.generated
     */
    public void setFollowingUrl(String followingUrl) {
        this.followingUrl = followingUrl == null ? null : followingUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.gists_url
     *
     * @return the value of t_user_github.gists_url
     *
     * @mbg.generated
     */
    public String getGistsUrl() {
        return gistsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.gists_url
     *
     * @param gistsUrl the value for t_user_github.gists_url
     *
     * @mbg.generated
     */
    public void setGistsUrl(String gistsUrl) {
        this.gistsUrl = gistsUrl == null ? null : gistsUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.starred_url
     *
     * @return the value of t_user_github.starred_url
     *
     * @mbg.generated
     */
    public String getStarredUrl() {
        return starredUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.starred_url
     *
     * @param starredUrl the value for t_user_github.starred_url
     *
     * @mbg.generated
     */
    public void setStarredUrl(String starredUrl) {
        this.starredUrl = starredUrl == null ? null : starredUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.subscriptions_url
     *
     * @return the value of t_user_github.subscriptions_url
     *
     * @mbg.generated
     */
    public String getSubscriptionsUrl() {
        return subscriptionsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.subscriptions_url
     *
     * @param subscriptionsUrl the value for t_user_github.subscriptions_url
     *
     * @mbg.generated
     */
    public void setSubscriptionsUrl(String subscriptionsUrl) {
        this.subscriptionsUrl = subscriptionsUrl == null ? null : subscriptionsUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.organizations_url
     *
     * @return the value of t_user_github.organizations_url
     *
     * @mbg.generated
     */
    public String getOrganizationsUrl() {
        return organizationsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.organizations_url
     *
     * @param organizationsUrl the value for t_user_github.organizations_url
     *
     * @mbg.generated
     */
    public void setOrganizationsUrl(String organizationsUrl) {
        this.organizationsUrl = organizationsUrl == null ? null : organizationsUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.repos_url
     *
     * @return the value of t_user_github.repos_url
     *
     * @mbg.generated
     */
    public String getReposUrl() {
        return reposUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.repos_url
     *
     * @param reposUrl the value for t_user_github.repos_url
     *
     * @mbg.generated
     */
    public void setReposUrl(String reposUrl) {
        this.reposUrl = reposUrl == null ? null : reposUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.events_url
     *
     * @return the value of t_user_github.events_url
     *
     * @mbg.generated
     */
    public String getEventsUrl() {
        return eventsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.events_url
     *
     * @param eventsUrl the value for t_user_github.events_url
     *
     * @mbg.generated
     */
    public void setEventsUrl(String eventsUrl) {
        this.eventsUrl = eventsUrl == null ? null : eventsUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.received_events_url
     *
     * @return the value of t_user_github.received_events_url
     *
     * @mbg.generated
     */
    public String getReceivedEventsUrl() {
        return receivedEventsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.received_events_url
     *
     * @param receivedEventsUrl the value for t_user_github.received_events_url
     *
     * @mbg.generated
     */
    public void setReceivedEventsUrl(String receivedEventsUrl) {
        this.receivedEventsUrl = receivedEventsUrl == null ? null : receivedEventsUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.type
     *
     * @return the value of t_user_github.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.type
     *
     * @param type the value for t_user_github.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.site_admin
     *
     * @return the value of t_user_github.site_admin
     *
     * @mbg.generated
     */
    public String getSiteAdmin() {
        return siteAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.site_admin
     *
     * @param siteAdmin the value for t_user_github.site_admin
     *
     * @mbg.generated
     */
    public void setSiteAdmin(String siteAdmin) {
        this.siteAdmin = siteAdmin == null ? null : siteAdmin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.company
     *
     * @return the value of t_user_github.company
     *
     * @mbg.generated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.company
     *
     * @param company the value for t_user_github.company
     *
     * @mbg.generated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.blog
     *
     * @return the value of t_user_github.blog
     *
     * @mbg.generated
     */
    public String getBlog() {
        return blog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.blog
     *
     * @param blog the value for t_user_github.blog
     *
     * @mbg.generated
     */
    public void setBlog(String blog) {
        this.blog = blog == null ? null : blog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.location
     *
     * @return the value of t_user_github.location
     *
     * @mbg.generated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.location
     *
     * @param location the value for t_user_github.location
     *
     * @mbg.generated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.email
     *
     * @return the value of t_user_github.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.email
     *
     * @param email the value for t_user_github.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.hireable
     *
     * @return the value of t_user_github.hireable
     *
     * @mbg.generated
     */
    public String getHireable() {
        return hireable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.hireable
     *
     * @param hireable the value for t_user_github.hireable
     *
     * @mbg.generated
     */
    public void setHireable(String hireable) {
        this.hireable = hireable == null ? null : hireable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.bio
     *
     * @return the value of t_user_github.bio
     *
     * @mbg.generated
     */
    public String getBio() {
        return bio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.bio
     *
     * @param bio the value for t_user_github.bio
     *
     * @mbg.generated
     */
    public void setBio(String bio) {
        this.bio = bio == null ? null : bio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.public_repos
     *
     * @return the value of t_user_github.public_repos
     *
     * @mbg.generated
     */
    public Integer getPublicRepos() {
        return publicRepos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.public_repos
     *
     * @param publicRepos the value for t_user_github.public_repos
     *
     * @mbg.generated
     */
    public void setPublicRepos(Integer publicRepos) {
        this.publicRepos = publicRepos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.public_gists
     *
     * @return the value of t_user_github.public_gists
     *
     * @mbg.generated
     */
    public Integer getPublicGists() {
        return publicGists;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.public_gists
     *
     * @param publicGists the value for t_user_github.public_gists
     *
     * @mbg.generated
     */
    public void setPublicGists(Integer publicGists) {
        this.publicGists = publicGists;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.followers
     *
     * @return the value of t_user_github.followers
     *
     * @mbg.generated
     */
    public Integer getFollowers() {
        return followers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.followers
     *
     * @param followers the value for t_user_github.followers
     *
     * @mbg.generated
     */
    public void setFollowers(Integer followers) {
        this.followers = followers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.following
     *
     * @return the value of t_user_github.following
     *
     * @mbg.generated
     */
    public Integer getFollowing() {
        return following;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.following
     *
     * @param following the value for t_user_github.following
     *
     * @mbg.generated
     */
    public void setFollowing(Integer following) {
        this.following = following;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.created_at
     *
     * @return the value of t_user_github.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.created_at
     *
     * @param createdAt the value for t_user_github.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.updated_at
     *
     * @return the value of t_user_github.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.updated_at
     *
     * @param updatedAt the value for t_user_github.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.private_gists
     *
     * @return the value of t_user_github.private_gists
     *
     * @mbg.generated
     */
    public Integer getPrivateGists() {
        return privateGists;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.private_gists
     *
     * @param privateGists the value for t_user_github.private_gists
     *
     * @mbg.generated
     */
    public void setPrivateGists(Integer privateGists) {
        this.privateGists = privateGists;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.total_private_repos
     *
     * @return the value of t_user_github.total_private_repos
     *
     * @mbg.generated
     */
    public Integer getTotalPrivateRepos() {
        return totalPrivateRepos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.total_private_repos
     *
     * @param totalPrivateRepos the value for t_user_github.total_private_repos
     *
     * @mbg.generated
     */
    public void setTotalPrivateRepos(Integer totalPrivateRepos) {
        this.totalPrivateRepos = totalPrivateRepos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.owned_private_repos
     *
     * @return the value of t_user_github.owned_private_repos
     *
     * @mbg.generated
     */
    public Integer getOwnedPrivateRepos() {
        return ownedPrivateRepos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.owned_private_repos
     *
     * @param ownedPrivateRepos the value for t_user_github.owned_private_repos
     *
     * @mbg.generated
     */
    public void setOwnedPrivateRepos(Integer ownedPrivateRepos) {
        this.ownedPrivateRepos = ownedPrivateRepos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.disk_usage
     *
     * @return the value of t_user_github.disk_usage
     *
     * @mbg.generated
     */
    public String getDiskUsage() {
        return diskUsage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.disk_usage
     *
     * @param diskUsage the value for t_user_github.disk_usage
     *
     * @mbg.generated
     */
    public void setDiskUsage(String diskUsage) {
        this.diskUsage = diskUsage == null ? null : diskUsage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.collaborators
     *
     * @return the value of t_user_github.collaborators
     *
     * @mbg.generated
     */
    public Integer getCollaborators() {
        return collaborators;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.collaborators
     *
     * @param collaborators the value for t_user_github.collaborators
     *
     * @mbg.generated
     */
    public void setCollaborators(Integer collaborators) {
        this.collaborators = collaborators;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.two_factor_authentication
     *
     * @return the value of t_user_github.two_factor_authentication
     *
     * @mbg.generated
     */
    public String getTwoFactorAuthentication() {
        return twoFactorAuthentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.two_factor_authentication
     *
     * @param twoFactorAuthentication the value for t_user_github.two_factor_authentication
     *
     * @mbg.generated
     */
    public void setTwoFactorAuthentication(String twoFactorAuthentication) {
        this.twoFactorAuthentication = twoFactorAuthentication == null ? null : twoFactorAuthentication.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.plan_name
     *
     * @return the value of t_user_github.plan_name
     *
     * @mbg.generated
     */
    public String getPlanName() {
        return planName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.plan_name
     *
     * @param planName the value for t_user_github.plan_name
     *
     * @mbg.generated
     */
    public void setPlanName(String planName) {
        this.planName = planName == null ? null : planName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.plan_space
     *
     * @return the value of t_user_github.plan_space
     *
     * @mbg.generated
     */
    public String getPlanSpace() {
        return planSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.plan_space
     *
     * @param planSpace the value for t_user_github.plan_space
     *
     * @mbg.generated
     */
    public void setPlanSpace(String planSpace) {
        this.planSpace = planSpace == null ? null : planSpace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.plan_collaborators
     *
     * @return the value of t_user_github.plan_collaborators
     *
     * @mbg.generated
     */
    public Integer getPlanCollaborators() {
        return planCollaborators;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.plan_collaborators
     *
     * @param planCollaborators the value for t_user_github.plan_collaborators
     *
     * @mbg.generated
     */
    public void setPlanCollaborators(Integer planCollaborators) {
        this.planCollaborators = planCollaborators;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.plan_private_repos
     *
     * @return the value of t_user_github.plan_private_repos
     *
     * @mbg.generated
     */
    public Integer getPlanPrivateRepos() {
        return planPrivateRepos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.plan_private_repos
     *
     * @param planPrivateRepos the value for t_user_github.plan_private_repos
     *
     * @mbg.generated
     */
    public void setPlanPrivateRepos(Integer planPrivateRepos) {
        this.planPrivateRepos = planPrivateRepos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.del_flag
     *
     * @return the value of t_user_github.del_flag
     *
     * @mbg.generated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.del_flag
     *
     * @param delFlag the value for t_user_github.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.create_by
     *
     * @return the value of t_user_github.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.create_by
     *
     * @param createBy the value for t_user_github.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.create_date
     *
     * @return the value of t_user_github.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.create_date
     *
     * @param createDate the value for t_user_github.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.update_by
     *
     * @return the value of t_user_github.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.update_by
     *
     * @param updateBy the value for t_user_github.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.update_date
     *
     * @return the value of t_user_github.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.update_date
     *
     * @param updateDate the value for t_user_github.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_github.version
     *
     * @return the value of t_user_github.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_github.version
     *
     * @param version the value for t_user_github.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}