spring:
  profiles:
    active: dev,local
  application:
    name: zimu
  mvc:
    static-path-pattern: /static/**
    favicon:
      enabled: false
  resources:
    chain:
      strategy:
        content:
          enabled: false
        fixed:
          enabled: false
          version: v1.0.0
      cache: true
    cache:
      period: 604800 #必须加缓存时间，默认秒
  thymeleaf:
    cache: false
  session:
    store-type: redis
    timeout: 2000
    redis:
      namespace: spring:session:${spring.application.name}
  messages:
    basename: i18n/messages/messages,i18n/system/messages
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: embedded
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      org.quartz.jobStore.isClustered: true #是否使用集群
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  liquibase:
    enabled: false
static:
  url-patterns:
    - /
    - /index.html
    - /error/**
    - /resources/**
    - /static/**
    - /public/**
    - /webjars/**
    - /test/**
    - /register/**
mybatis-plus:
  type-aliases-package: com.zimu.entity
  mapper-locations: classpath:com/zimu/mapper/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler
  type-enums-package: com.zimu.common.mybatisplus.enums
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 9001

---

spring:
  profiles: local
logging:
  config: classpath:log4j2.xml
server:
  port: 8080