package com.zimu.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.zimu.domain.entity.DictEntity;
import com.zimu.domain.entity.DictEntityExample;

public interface DictEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbg.generated
     */
    long countByExample(DictEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbg.generated
     */
    int deleteByExample(DictEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbg.generated
     */
    int insert(DictEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbg.generated
     */
    int insertSelective(DictEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbg.generated
     */
    List<DictEntity> selectByExample(DictEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbg.generated
     */
    DictEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DictEntity record, @Param("example") DictEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DictEntity record, @Param("example") DictEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DictEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DictEntity record);
}