package com.zimu.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.zimu.domain.entity.PersistentLoginsEntity;
import com.zimu.domain.entity.PersistentLoginsEntityExample;

public interface PersistentLoginsEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbg.generated
     */
    long countByExample(PersistentLoginsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbg.generated
     */
    int deleteByExample(PersistentLoginsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String series);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbg.generated
     */
    int insert(PersistentLoginsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbg.generated
     */
    int insertSelective(PersistentLoginsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbg.generated
     */
    List<PersistentLoginsEntity> selectByExample(PersistentLoginsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbg.generated
     */
    PersistentLoginsEntity selectByPrimaryKey(String series);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PersistentLoginsEntity record, @Param("example") PersistentLoginsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PersistentLoginsEntity record, @Param("example") PersistentLoginsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PersistentLoginsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PersistentLoginsEntity record);
}