package com.zimu.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.zimu.domain.entity.RequestMappingEntity;
import com.zimu.domain.entity.RequestMappingEntityExample;

public interface RequestMappingEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_mapping
     *
     * @mbg.generated
     */
    long countByExample(RequestMappingEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_mapping
     *
     * @mbg.generated
     */
    int deleteByExample(RequestMappingEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_mapping
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_mapping
     *
     * @mbg.generated
     */
    int insert(RequestMappingEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_mapping
     *
     * @mbg.generated
     */
    int insertSelective(RequestMappingEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_mapping
     *
     * @mbg.generated
     */
    List<RequestMappingEntity> selectByExample(RequestMappingEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_mapping
     *
     * @mbg.generated
     */
    RequestMappingEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_mapping
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RequestMappingEntity record, @Param("example") RequestMappingEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_mapping
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RequestMappingEntity record, @Param("example") RequestMappingEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_mapping
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RequestMappingEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_mapping
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RequestMappingEntity record);
}