package com.zimu.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.zimu.domain.entity.UserGithubEntity;
import com.zimu.domain.entity.UserGithubEntityExample;

public interface UserGithubEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_github
     *
     * @mbg.generated
     */
    long countByExample(UserGithubEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_github
     *
     * @mbg.generated
     */
    int deleteByExample(UserGithubEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_github
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_github
     *
     * @mbg.generated
     */
    int insert(UserGithubEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_github
     *
     * @mbg.generated
     */
    int insertSelective(UserGithubEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_github
     *
     * @mbg.generated
     */
    List<UserGithubEntity> selectByExample(UserGithubEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_github
     *
     * @mbg.generated
     */
    UserGithubEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_github
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserGithubEntity record, @Param("example") UserGithubEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_github
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserGithubEntity record, @Param("example") UserGithubEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_github
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserGithubEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_github
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserGithubEntity record);
}